spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fo_db
    username: root
    password: alunoinfo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format-sql: true



server:
  ssl:
    key-store-type: jks
    key-store: classpath:object-finder-app-api-https.jks
    key-store-password: password
    key-alias: object-finder-app-api-https
    enabled: true
  port: 8080